### ISSUE TITLE
Assuming no rotation between blocks during matching?

### ISSUE THREAD

**Issue by waltzina** [Jamy-L/Handheld-Multi-Frame-Super-Resolution#16]
Hi this repo contains really nice and detailed implementation and explanation. I have a more methodology question: I'm reading your IPOL paper, and judging from eq1, it appears the registration algorithms assume no rotational mismatch between blocks from different frames. Could you please kindly confirm that, or am I missing something? Thank you.

**Comment by Jamy-L** [comment]
Hi, it is indeed assumed that the optical flow is a patchwise translation, which explains why only 2 parameters are estimated per patch for each frame. We have also tried to estimate more complex models, but it made the execution much slower and resulted in very visible merging artifact.
Thank you for you interest, and feel free to ask if you have more question.
