### ISSUE TITLE
when set 'kernel_shape=iso', run with cuda error, don't support this param?

### ISSUE THREAD

**Issue by renwoxing000** [Jamy-L/Handheld-Multi-Frame-Super-Resolution#24]

**Comment by Jamy-L** [comment]
Hi, after checking on my side on the latest version, I had no such problem. Make sure you are specifying the shape like this :
```python
params={
        "scale":2,
        "merging" : {
            'kernel': 'iso'},
        }
```

If the problem persists, please use a verbose of level 4 using : 
```python
options = {'verbose': 4}
```
and print what you get. 

Best,
Jamy

**Comment by renwoxing000** [comment]
Hi Jamy: 

I check the demo with param 'kernel = iso' in newest code, there is no problem. 

By the way,  the param transmission has some problem. 
when config params like this:
params={
        "scale":2,
        "merging" : {
            'kernel': 'iso'},
        }

Param "kernel iso " not valid in the function "merge()". The reason of no valid is the params of 'kernel' is overwrite by param init process.

**Comment by renwoxing000** [comment]
Hi Jamy:

The results of isotropic kernel and  anisotropic kernel looks like same ?

**Comment by Jamy-L** [comment]
Hi, after checking everything on my side, I have found no issue with the transmission of the parameters. the function `merge()` takes the params dictionnary as input and reads it as expected. For the results, the difference has been illustrated in the article and can be observed by zooming agressively : isotropic kernels make edges more blurry and are not as good as steerable kernels for denoising

**Comment by renwoxing000** [comment]
I will check again, thanks.
