### ISSUE TITLE
Result color problem

### ISSUE THREAD

**Issue by Destiny-Dream1** [Jamy-L/Handheld-Multi-Frame-Super-Resolution#30]
Hello, I noticed that when running your program, the colors in the generated results appear different from the low-resolution images. I'm not sure if this is normal. I have tried adjusting various parameters, but I couldn't match the colors with the low-resolution photos. 

I have attached my results. The left side is the low-resolution first frame, the middle is the super-resolution result with color correction, and the right side is the super-resolution result without color correction.

Thank you so much.
![question](https://github.com/Jamy-L/Handheld-Multi-Frame-Super-Resolution/assets/72513073/7a5f8b6f-594b-4bdc-82d3-1c7be3ba4458)

**Comment by teboli** [comment]
Destiny-Dream1, 

It looks like a white balance problem to me. You closed the issue so I suppose you solved the problem. If so, what was the cause so it can help other users? Thanks!

Thomas

**Comment by Destiny-Dream1** [comment]
Hello, I'm not entirely sure how I obtained this photo. Afterwards, I couldn't reproduce this result by converting DNG to any other file format. I personally think it might be an issue with RGB and BGR, so I've closed this issue for now. Thank you very much for the responses from the authors.

**Comment by teboli** [comment]
Ok thanks! If it's a matter of Bayer pattern, eg you have BGGR instead of the expected RGGB format, you can rotate by 180 degrees the raw images right after reading the raw files and you should be good.
