### ISSUE TITLE
Google cloud disk links are invalidated

### ISSUE THREAD

**Issue by Tara-Liu** [Jamy-L/Handheld-Multi-Frame-Super-Resolution#40]
Hello, thank you very much for your work. The Google cloud disk link for testing the image has failed. Can you upload it again? Thank you very much

**Comment by Jamy-L** [comment]
Hi, you are right the google drive link was down, I ended up removing it from the readme to avoid adding more external dependencies. The test bursts are directly packed inside [the latest relase](https://github.com/Jamy-L/Handheld-Multi-Frame-Super-Resolution/releases/tag/v1.2.0).

**Comment by dhruvi18022004** [comment]
> Hi, you are right the google drive link was down, I ended up removing it from the readme to avoid adding more external dependencies. The test bursts are directly packed inside [the latest relase](https://github.com/Jamy-L/Handheld-Multi-Frame-Super-Resolution/releases/tag/v1.2.0). 

Hello, Jamy-L the google drive link which is in test burst folder is not working or another option you share like from deep-repo we can also download the dataset but in that  repo there are multiple dataset, so whcih dataset is relatable to our repo and which dataset is containing dng files? could you please help me to find out the dataset?

**Comment by Jamy-L** [comment]
> Hello, Jamy-L the google drive link which is in test burst folder is not working or another option you share like from deep-repo we can also download the dataset but in that repo there are multiple dataset, so whcih dataset is relatable to our repo and which dataset is containing dng files? could you please help me to find out the dataset?

Downloading the .dng from de the deep burst SR is a bit tricky if I remember well, I had to find a server url in one of their scripts to manually download the bursts . I prefer not to use google drive, but if you download the release zip the burst will be inside. See commit 17199c3 .

If there is a an issue with the release and the bursts, please let me know 😊
